version: '3.9'

services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auto_fare
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/auto_fare

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  db_data:
